# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b3f3744ca15f7c343e8da92a8d9b8650983acec045c8f2f7aedff93193b6a6b92dab9b5e965893d381cd3a709bac5dc356152eeff97e60cd14c5cbe59e62a95

test:
  secret_key_base: 1f6d2a41b08dc06274088cedf0bd2d728e0845115c528bdf6f2e46d31b0439f30e8f5778458ff9c8fa195ba8f50edb37ef2189fe26c289c78fa49a76857e1fb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
